name: timesheets
description: Табели посещаемости

version: 2023.2.3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  intl:
  sqflite:
  drift:
  sqlite3:
  sqlite3_flutter_libs:
  path:
  path_provider:
  rxdart:
  provider:
  flutter_markdown:
  share:
  uri_to_file:
  http:
  http_parser:
  qr_flutter:
  url_launcher: ^6.1.7
  file_picker: ^5.2.5

dev_dependencies:
  drift_dev:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  build_web_compilers:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_timesheets_512.png"
  web:
    generate: true
    image_path: "assets/icons/ic_timesheets_512.png"
    background_color: "#ffffff"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/ic_timesheets_512.png"
    icon_size: 256 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/