name: timesheets
description: Табели посещаемости

version: 2022.5.31

environment:
  sdk: ">=2.8.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  intl:
  sqflite:
  drift:
  sqlite3_flutter_libs:
  path_provider:
  rxdart:
  provider:
  month_picker_dialog:
  horizontal_data_table:
  flutter_markdown:
  url_launcher:
  share:
  file_picker:
  uri_to_file:
  http:

dev_dependencies:
  drift_dev:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_timesheets_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/