name: timesheets
description: Табели посещаемости в детсадах и доп.образовании

version: 2021.7.2

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  intl:
  sqflite:
  moor: ^4.3.2
  sqlite3_flutter_libs:
  path_provider:
  rxdart: ^0.24.0
  provider:
  month_picker_dialog: ^0.3.3
  horizontal_data_table:
  flutter_markdown:
  url_launcher:
  permission_handler:
  share:
  file_picker:

dev_dependencies:
  moor_generator: ^4.3.2
  build_runner:
  flutter_launcher_icons:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_timesheets_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/