name: timesheets
description: Табели посещаемости в группах по графикам

version: 2020.10.16

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  intl:
  sqflite:
  moor:
  sqlite3_flutter_libs:
  path_provider:
  rxdart:
  provider:
  month_picker_dialog:
  horizontal_data_table:
  flutter_markdown:
  url_launcher:
  permission_handler:
  flutter_share_content:
  file_picker:
  uni_links:

dev_dependencies:
  moor_generator: ^3.3.1
  build_runner: ^1.10.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_timesheets_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/