name: timesheets
description: Табели посещаемости людей в группах по графикам

version: 0.1.0

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  injector:
  intl:
  sqflite:
  moor:
  moor_ffi: "0.5.0"
  path_provider:
  rxdart:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  moor_generator:
  build_runner:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_timesheets_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
